language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "dpjames-github"
    token:
      secure: "459554e75e21bfbfb1da7c126282053aa401d72a"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
